# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnled = QtWidgets.QPushButton(self.centralwidget)
        self.btnled.setGeometry(QtCore.QRect(40, 50, 93, 29))
        self.btnled.setObjectName("btnled")
        self.btnmotor = QtWidgets.QPushButton(self.centralwidget)
        self.btnmotor.setGeometry(QtCore.QRect(290, 50, 93, 29))
        self.btnmotor.setObjectName("btnmotor")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 170, 91, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.labelcb = QtWidgets.QLabel(self.centralwidget)
        self.labelcb.setGeometry(QtCore.QRect(290, 140, 181, 20))
        self.labelcb.setText("")
        self.labelcb.setObjectName("labelcb")
        self.btnsubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnsubmit.setGeometry(QtCore.QRect(290, 210, 93, 29))
        self.btnsubmit.setObjectName("btnsubmit")
        self.btntype = QtWidgets.QPushButton(self.centralwidget)
        self.btntype.setGeometry(QtCore.QRect(40, 210, 99, 30))
        self.btntype.setObjectName("btntype")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(40, 170, 50, 32))
        self.spinBox.setObjectName("spinBox")
        self.labelsb = QtWidgets.QLabel(self.centralwidget)
        self.labelsb.setGeometry(QtCore.QRect(40, 140, 181, 20))
        self.labelsb.setText("")
        self.labelsb.setObjectName("labelsb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnled.setText(_translate("MainWindow", "OFF"))
        self.btnmotor.setText(_translate("MainWindow", "OFF"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Python"))
        self.comboBox.setItemText(1, _translate("MainWindow", "JAVA"))
        self.comboBox.setItemText(2, _translate("MainWindow", "C++"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ruby"))
        self.btnsubmit.setText(_translate("MainWindow", "Submit"))
        self.btntype.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
